//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class dizhi
    {
        public int dizhiID { get; set; }
        public string dizhiName { get; set; }
        public string linkman { get; set; }
        public string phone { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> KehuID { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
