//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class gysguanli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gysguanli()
        {
            this.ruku = new HashSet<ruku>();
        }
    
        public int GID { get; set; }
        public Nullable<int> gystypeID { get; set; }
        public string GName { get; set; }
        public string phone { get; set; }
        public string faxes { get; set; }
        public string Email { get; set; }
        public string linkman { get; set; }
        public string address { get; set; }
        public string describe { get; set; }
        public Nullable<int> state { get; set; }
        public string by1 { get; set; }
        public string by2 { get; set; }
    
        public virtual gystype gystype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ruku> ruku { get; set; }
    }
}
