//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class jurisdiction
    {
        public int JID { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> MID { get; set; }
        public Nullable<int> state { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual role role { get; set; }
    }
}
