//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menu()
        {
            this.jurisdiction = new HashSet<jurisdiction>();
        }
    
        public int MID { get; set; }
        public string MNmae { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string style { get; set; }
        public string sort { get; set; }
        public string path { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jurisdiction> jurisdiction { get; set; }
        public virtual MenuType MenuType { get; set; }
        public virtual Parentmenu Parentmenu { get; set; }
    }
}
