//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage
    {
        public int TID { get; set; }
        public string KName { get; set; }
        public Nullable<int> WID { get; set; }
        public Nullable<int> KuTypeID { get; set; }
        public string forbidden { get; set; }
        public string @default { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> state { get; set; }
        public string by1 { get; set; }
        public string by2 { get; set; }
    
        public virtual KuType KuType { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
