//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class yikuxq
    {
        public int yikuxqID { get; set; }
        public Nullable<int> chanpinID { get; set; }
        public string chanpinName { get; set; }
        public string chanpintiaoma { get; set; }
        public Nullable<int> chanpinPrice { get; set; }
        public Nullable<int> yikusum { get; set; }
        public Nullable<int> chanpinpici { get; set; }
        public Nullable<int> yikuTypeID { get; set; }
        public Nullable<int> kehuID { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual yikuType yikuType { get; set; }
    }
}
