//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewHope4Entities : DbContext
    {
        public NewHope4Entities()
            : base("name=NewHope4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<baosun> baosun { get; set; }
        public virtual DbSet<baosunType> baosunType { get; set; }
        public virtual DbSet<BSxiang> BSxiang { get; set; }
        public virtual DbSet<chuku> chuku { get; set; }
        public virtual DbSet<chukuType> chukuType { get; set; }
        public virtual DbSet<CKxiang> CKxiang { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<dizhi> dizhi { get; set; }
        public virtual DbSet<gysguanli> gysguanli { get; set; }
        public virtual DbSet<gystype> gystype { get; set; }
        public virtual DbSet<jurisdiction> jurisdiction { get; set; }
        public virtual DbSet<KuType> KuType { get; set; }
        public virtual DbSet<measurement> measurement { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<MenuType> MenuType { get; set; }
        public virtual DbSet<panDian> panDian { get; set; }
        public virtual DbSet<pandianType> pandianType { get; set; }
        public virtual DbSet<pandianxq> pandianxq { get; set; }
        public virtual DbSet<Parentmenu> Parentmenu { get; set; }
        public virtual DbSet<productguanli> productguanli { get; set; }
        public virtual DbSet<productType> productType { get; set; }
        public virtual DbSet<RKxiang> RKxiang { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<roleType> roleType { get; set; }
        public virtual DbSet<ruku> ruku { get; set; }
        public virtual DbSet<rukuType> rukuType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tuihuo> tuihuo { get; set; }
        public virtual DbSet<tuihuoType> tuihuoType { get; set; }
        public virtual DbSet<tuihuoxq> tuihuoxq { get; set; }
        public virtual DbSet<warehouse> warehouse { get; set; }
        public virtual DbSet<yiku> yiku { get; set; }
        public virtual DbSet<yikuType> yikuType { get; set; }
        public virtual DbSet<yikuxq> yikuxq { get; set; }
        public virtual DbSet<storage> storage { get; set; }
    }
}
